services:
  backend:
    build: ./VocabQuest/backend
    user: root
    ports:
      - "5001:5001"
    volumes:
      - ./VocabQuest/backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python app.py

  frontend:
    build: ./VocabQuest/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./VocabQuest/frontend/src:/app/src
      - ./VocabQuest/frontend/public:/app/public

    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - backend
